---

- name: configure DOCKER_OPTS for swarm in mesos
  lineinfile: dest=/etc/default/docker
              regexp="^DOCKER_OPTS='--graph"
              backrefs=yes
              line="DOCKER_OPTS='--graph=/openstack/docker --storage-driver=devicemapper --dns=8.8.8.8 --iptables=false --default-ulimit nofile=65536:65536 --default-ulimit nproc=50000:50000 -H tcp://0.0.0.0:8089 -H unix:///var/run/docker.sock --ip-forward=false --log-opt max-size=1m --log-opt max-file=2'"
  register: cmd_result

- service: name=docker state=restarted
  when: cmd_result.changed
