---
 - hosts: [lb]
   become: yes
   vars_files:
    - ../../../../envs/dev-mon01/defaults.yml
   tasks:
    - name: including the variables
      include_vars: ../../../group_vars/all
    - name: create haproxy.cfg
      file: path=/tmp/hap_config  state=directory mode=0644
    - name: generate and copy HAproxy config
      template: src=../files/haproxyConfig.j2 dest=/tmp/hap_config/haproxy.cfg
    - name: run haproxy in a container
      docker:
       name: haproxy
       image: "{{haproxy_image}}"
       pull: missing
       restart_policy: always
       state: present
       privileged: yes
       net: host
       volumes:
        - /tmp/hap_config/:/usr/local/etc/haproxy/
       command: -f /usr/local/etc/haproxy/haproxy.cfg
    - name: copy HTTP start/stop scripts
      copy: src=../files/HTTP-actions.sh dest=/tmp/HTTP-actions.sh owner={{ansible_ssh_user}} mode=0766
