language: python
python:
  - "2.7"

install:
  - pip install yamllint

script: yamllint -c yamlconf $(find . -path './envs' -prune -o -name '*.yml' -print -o -name '*.yaml' -print)

notifications:
  email: true
  slack:
    rooms:
      - blue-alchemy:OTG2kwQwHRx8ZieTwB3WsrVD#dove-github
    on_start: never
    on_failure: always
    on_success: change
    on_pull_requests: false
