---
#  - include_vars: group_vars/all

  - name: set zk_id
    set_fact: zoo_id="{% for thishost in groups['zk-' ~ cluster_name] %}{% if inventory_hostname==thishost %}{{ loop.index }}{% endif %}{% endfor %}"

  - name: set zk_servers
    set_fact: zookeeper_hosts="{% for host in groups['zk-' ~ cluster_name] %}{{ host }},{{ loop.index }}{% if not loop.last %};{% endif %}{% endfor %}"

  - name: deploy zookeeper
    register: command_result
    failed_when: "command_result.status is defined and 'legacy registry' not in command_result.status"
    docker:
     name: zookeeper
     image: "{{zookeeper_image}}"
     pull: always
     state: reloaded
     restart_policy: always
     command:  --servers "{{ zookeeper_hosts }}" --id "{{ zoo_id }}"
     privileged: yes
     net: host
     ports:
      - "{{zookeeper_port}}:{{zookeeper_port}}"
     volumes:
      - /var/log:/var/log/supervisor:rw
