---

- include: flannel-config-in-etcd.yaml
  when: inventory_hostname == groups['etcd-' ~ cluster_name][0]

- include: worker-prep.yaml
  when: inventory_hostname in groups['workers-' ~ cluster_name]
