---

- name: ensure user's tmp dir exists
  file:
    dest: "{{ ansible_user_dir }}/tmp/{{ cluster_name }}"
    state: directory

- name: fetch Flannel archive
  get_url:
    dest: "{{ ansible_user_dir }}/tmp/"
    force: no
    url: https://github.com/coreos/flannel/releases/download/v{{flannel_version}}/flannel-{{flannel_version}}-linux-amd64.tar.gz

- name: unarchive Flannel
  unarchive:
    src: "{{ ansible_user_dir }}/tmp/flannel-{{flannel_version}}-linux-amd64.tar.gz"
    dest: "{{ ansible_user_dir }}/tmp/"
    creates: "{{ ansible_user_dir }}/tmp/flannel-{{flannel_version}}/flanneld"

- name: fetch Flannel upstart service
  get_url:
    dest: "{{ ansible_user_dir }}/tmp/"
    force: no
    url: https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.3/cluster/ubuntu/minion-flannel/init_conf/flanneld.conf
