---

- name: set zookeeper_url
  set_fact: zookeeper_url="zk://{% for host in groups['zk-' ~ cluster_name] %}{{ host }}:{{ zookeeper_port }}{% if not loop.last %},{% endif %}{% endfor %}"

- name: set mesos quorum
  set_fact: mesos_quorum="{{ ((groups['mesos_master-' ~ cluster_name]|length) // 2) + 1 }}"

- set_fact: roles="--roles={{mesos_roles | join(',')}}"
  when: use_mesos_roles|bool

- set_fact: roles=""
  when: not use_mesos_roles|bool

- name: "Pulling image {{ mesos_master_image }}"
  shell: docker pull "{{ mesos_master_image }}"
  when: infrastructure_docker_registry_type == 'v1'

- name: deploy mesos master
  docker:
    name: mesos
    image: "{{mesos_master_image}}"
    pull: "{{image_pull_type}}"
    state: reloaded
    restart_policy: always
    env:
      MESOS_LOG_DIR: /var/log/mesos
      MESOS_WORK_DIR: /var/tmp/mesos
    command: >
              --ip={{ inventory_hostname }}
              --no-hostname_lookup
              --zk={{ zookeeper_url }}/mesos
              --quorum={{ mesos_quorum }}
              --allocation_interval={{ mesos_allocation_interval }}
              {{roles}}
    privileged: yes
    net: host
    ports:
      - "{{mesos_master_port}}:{{mesos_master_port}}"
