---
 - hosts: [etcd]
   become: yes
   user: radiant
   vars_files:
    - ../../../../envs/dev-mon01/defaults.yml
    - ../../../group_vars/all

   tasks:
    #- include_vars: ../../../group_vars/all
    - name: create etcd data directory
      file: path=/var/etcd/data state=directory mode=766
    - name: set initial_cluster_nodes
      set_fact: initial_cluster_nodes="{% for host in groups['etcd'] %}etcd{{loop.index -1}}=http://{{ host }}:{{etcd_advertise_peer_port}}{% if not loop.last %},{% endif %}{% endfor %}"
    - name: pull docker image
      shell: docker pull "{{etcd_image}}"
    - name: start etcd in a container
      docker:
       name: etcd{{groups.etcd.index(inventory_hostname)}}
       state: reloaded
       pull: missing
       restart_policy: always
       image: "{{etcd_image}}"
       command: >
            -name etcd{{groups.etcd.index(inventory_hostname)}}
            -data-dir /var/etcd/data
            -advertise-client-urls http://{{inventory_hostname}}:{{etcd_listen_client_port}}
            -listen-client-urls http://0.0.0.0:{{etcd_listen_client_port}}
            -initial-advertise-peer-urls http://{{inventory_hostname}}:{{etcd_advertise_peer_port}}
            -listen-peer-urls http://0.0.0.0:{{etcd_advertise_peer_port}}
            -initial-cluster-token etcd-cluster-1
            -initial-cluster {{initial_cluster_nodes}}
            -initial-cluster-state new
       net: bridge
       expose:
        - "{{etcd_listen_client_port}}"
        - "{{etcd_advertise_peer_port}}"
       ports:
        - "{{etcd_listen_client_port}}:{{etcd_listen_client_port}}"
        - "{{etcd_advertise_peer_port}}:{{etcd_advertise_peer_port}}"
       volumes:
        - "/var/etcd/data:/var/etcd/data"
