apiVersion: v1
kind: Pod
metadata:
  name: kube-web-ms
  labels:
    app: web-ms-demo
spec:
  containers:
    - name: kube-web-server
      image: mrsabath/web-ms:v3
      ports:
        - containerPort: 80
      env:
        -
         name: "TEST"
         value: "web-server"
