---

- hosts:
    - localhost
  gather_facts: no
  tasks:
  - debug: msg="environment name is '{{env_name}}', envs are in '{{envs}}'"

  - name: import environment defaults
    include_vars: "{{envs}}/{{env_name}}/defaults.yml"
