---

- hosts:
    - localhost
  gather_facts: no
  tasks:
  - name: parse cluster name
    delegate_to: localhost
    shell: echo "{{cluster_name}}" | cut -d- -f1,2; echo "{{cluster_name}}" | cut -d- -f3-
    register: nameres
    changed_when: False

  - set_fact:
      env_name: "{{ nameres.stdout_lines[0] }}"

  - debug: msg="environment name is '{{env_name}}', envs are in '{{envs}}'"

  - name: import environment defaults
    include_vars: "{{envs}}/{{env_name}}/defaults.yml"
