---

- hosts:
    - cluster-{{cluster_name}}
    - localhost
  tasks:
  - debug: msg="network plugin is {{network_kind}}"

- hosts:
    - cluster-{{cluster_name}}
    - localhost
  roles:
  - "{{ network_kind }}-variables"
