---
- include: ./load-vars-cluster.yml

- hosts:
    - cluster-{{cluster_name}}
    - localhost
  tasks:
  - debug: msg="network plugin is {{network_kind}}"

- hosts:
    - cluster-{{cluster_name}}
    - localhost

  pre_tasks:
  - name: Set secondary variables of networking to their initial values
    set_fact:
      k8s_kubelet_network_args: []
      use_kube_system_kubedns: False

  roles:
  - "{{ network_kind }}-variables"

  post_tasks:
  - name: Set etcd_deploy to True if other settings imply deploying etcd
    set_fact:
      etcd_deploy: True
    when: kubernetes_deploy

- hosts: localhost
  tasks:
  - fail:
      msg: ha_deploy must be True when there are multiple hosts in the mesos_master-{{ cluster_name }} group in your Ansible inventory
    when: groups['mesos_master-' ~ cluster_name]|length > 1 and not ha_deploy

- hosts: localhost
  roles:
  - "{{ network_kind }}-local-prep"

- hosts: cluster-{{cluster_name}}
  become: yes
  roles:
  - prereqs
  - common

- hosts: localhost
  roles:
  - keygen

- hosts: zk-{{cluster_name}}
  become: yes
  roles:
  - { role: zk, when: "mesos_deploy" }

- hosts: etcd-{{cluster_name}}
  become: yes
  roles:
  - { role: etcd, when: "etcd_deploy" }

- hosts: cluster-{{cluster_name}}
  become: yes
  roles:
  - role: "{{ network_kind }}-remote-prep"

- hosts: mesos_master-{{cluster_name}}
  become: yes
  roles:
  - { role: mesos-master, when: "mesos_deploy" }

- hosts: lb-{{cluster_name}}
  become: yes
  roles:
  - lb
  - { role: vip, when: "groups['mesos_master-' ~ cluster_name]|length > 1 or ha_deploy" }

- hosts: k8s_auth-{{cluster_name}}
  become: yes
  roles:
  - auth

- hosts: k8s_master-{{cluster_name}}
  become: yes
  roles:
  - { role: k8sm-master, when: "kubernetes_deploy" }

- hosts: swarm_master-{{cluster_name}}
  become: yes
  roles:
  - { role: swarm-master, when: "swarm_deploy" }

- hosts: workers-{{cluster_name}}
  become: yes
  roles:
  - { role: mesos-worker, when: "mesos_deploy" }
  - { role: k8sm-worker, when: "kubernetes_deploy" }
  - { role: swarm-worker, when: "swarm_deploy" }

- hosts: k8s_master-{{cluster_name}}
  become: yes
  roles:
  - role: k8s-system-kubedns
    when: >
      use_kube_system_kubedns and
      inventory_hostname == groups['k8s_master-' ~ cluster_name][0]
