---
- include: ./utils/load-vars-cluster.yml

- hosts: localhost
  tasks:
  - name: check value of network_kind
    assert: { that: "network_kind in ('bridge', 'flannel')" }

- hosts: localhost
  roles:
  - { role: flannel-local-prep, when: "network_kind == 'flannel'" }

- hosts: cluster-{{cluster_name}}
  become: yes
  roles:
  - prereqs
  - common

- hosts: localhost
  roles:
  - keygen

- hosts: zk-{{cluster_name}}
  become: yes
  roles:
  - zk

- hosts: mesos_master-{{cluster_name}}
  become: yes
  roles:
  - mesos-master

- hosts: etcd-{{cluster_name}}
  become: yes
  roles:
  - etcd
  - role: flannel-config-in-etcd
    when: "network_kind == 'flannel' and inventory_hostname == groups['etcd-' ~ cluster_name][0]"

- hosts: lb-{{cluster_name}}
  become: yes
  roles:
  - lb
  - { role: vip, when: "groups['mesos_master-' ~ cluster_name]|length > 1" }

- hosts: k8s_auth-{{cluster_name}}
  become: yes
  roles:
  - auth

- hosts: k8s_master-{{cluster_name}}
  become: yes
  roles:
  - k8sm-master

- hosts: swarm_master-{{cluster_name}}
  become: yes
  roles:
  - swarm-master
