---
  - name: install ucarp
    apt: pkg=ucarp state=installed

  - name: add if-up.d script
    template: src=etc/network/if-up.d/vip dest=/etc/network/if-up.d/vip mode=0755

  - name: add up/down scripts for ucarp
    template: src=etc/network/{{ item }} dest=/etc/network/{{ item }} mode=0755
    with_items:
     - vip-down.sh
     - vip-up.sh

  - name: Start ucarp
    command: /etc/network/if-up.d/vip
    environment:
      IFACE: '{{ vip.interface }}'
      IF_ADDRESS: '{{ inventory_hostname }}'

  #- name: Wait for vip address to be reachable
    #wait_for: host="{{ vip.ip_address }}" port=22 state=started

  - name: "Create ucarp upstart service"
    template: src=vip_upstart.tmpl dest=/etc/init/ucarp_upstart.conf
