---

# Tasks for setting up the installation prereqs
- stat: path=/var/lib/apt/lists/lock
  register: apt_lock

- name: create apt lock file if it doesn't exist
  become: yes
  shell: "mkdir -p /var/lib/apt/lists && touch /var/lib/apt/lists/lock"
  when: not apt_lock.stat.exists

- name: apt-get update
  apt:
    update_cache: yes
  register: agu_rslt

- name: Install prereqs
  apt: name={{item}} state=present
  with_items:
       - curl
       - vim
       - ntp
       - python-pip
       - libsystemd-journal0
       - ufw

# install docker
- name: Add docker apt keys
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Update apt
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present

- name: Install Docker
  apt: pkg={{docker_package}} update_cache=yes state=present
  register: docker_installed

- name: add the ssh user to the docker group
  user: name={{ansible_ssh_user}} groups=docker append=yes

- name: make sure required PyPi packages are installed
  pip: name={{ item }} state=present
  with_items:
     - docker-py==1.5.0

- name: enable ufw logging
  ufw: logging=on

- name: Permit SSH in
  ufw: rule=allow to_port=22 proto=tcp interface={{network_interface}} direction=in

- name: Enable UFW. Allow everything
  ufw: state=enabled policy=allow
