---

- name: set zookeeper_url
  set_fact: zookeeper_url="zk://{% for host in groups['zk-' ~ cluster_name] %}{{ host }}:{{ zookeeper_port }}{% if not loop.last %},{% endif %}{% endfor %}"

- name: set mesos quorum
  set_fact: mesos_quorum="{{ ((groups['mesos_master-' ~ cluster_name]|length) // 2) + 1 }}"

- set_fact: roles="--roles={{mesos_roles | join(',')}}"
  when: use_mesos_roles|bool

- set_fact: roles=""
  when: not use_mesos_roles|bool

- name: deploy mesos master
  register: command_result
  failed_when: "command_result.status is defined and 'legacy registry' not in command_result.status"
  docker:
    name: mesos
    image: "{{mesos_master_image}}"
    pull: always
    state: reloaded
    restart_policy: always
    command: --ip={{ inventory_hostname }} --no-hostname_lookup --zk={{ zookeeper_url }}/mesos --quorum={{ mesos_quorum }} --allocation_interval={{ mesos_allocation_interval }} {{roles}}
    privileged: yes
    net: host
    ports:
      - "{{mesos_master_port}}:{{mesos_master_port}}"
