---

- name: "Create directory {{ k8s_cert_dir }}"
  file: path={{ k8s_cert_dir }} state=directory mode=0755

- name: "Copy CA cert"
  copy: src={{ cert_dir }}/{{ ca_cert }} dest={{ k8s_cert_dir }}/ mode=0644

- name: "Copy kubelet key"
  copy: src={{ cert_dir }}/{{ k8s_kubelet_cn }}.pem dest={{ k8s_cert_dir }}/ mode=0644

- name: "Copy kubelet cert"
  copy: src={{ cert_dir }}/{{ k8s_kubelet_cn }}-key.pem dest={{ k8s_cert_dir }}/ mode=0644
