---
vip:
   enabled: false
   interface: '{{network_interface}}'
   ip_address: '{{ master_vip }}'
   cidr_prefix: '/{{ master_vip_net_prefix_len }}'
   up_script: '/etc/network/vip-up.sh'
   down_script: '/etc/network/vip-down.sh'
   # id: Id number.  This needs to be the same for all hosts using the same vip [1-255]
   ucarp_id: '1'
   # password : A password used to encrypt Carp communications
   ucarp_password: 'thesecret'
   # advskew : Advertisement skew [1-255]
   ucarp_advskew: 100
   # advbase : Interval in seconds that advertisements will occur
   ucarp_advbase: 1
   # master : determine if this server is the master (no=let ucarp pick the master)
   ucarp-master: 'no'
